### ISSUE TITLE
Deprecate environment variables in favor of ConfigMap 

### ISSUE THREAD

**Issue by pires** [pires/kubernetes-nats-cluster#7]
See [ConfigMap documentation](http://kubernetes.io/docs/user-guide/configmap/).

**Comment by bmcustodio** [comment]
This would come in handy in downstream [nats-operator](https://github.com/pires/nats-operator), especially given the fact that one can send a `SIGHUP` to `gnatsd` to force a configuration reload.

I think the most useful way is to store the full NATS configuration in a `ConfigMap` and then use it to populate a volume:

```yaml
apiVersion: v1
kind: ConfigMap
data:
  nats.conf: |
    debug: true

    authorization {
      user: nats_user
      password: $WE_CAN_READ_THIS_FROM_AN_ENVVAR_CONTAINING_A_SECRET
    }

    cluster {
      host: '0.0.0.0'
      port: 6222

      routes = [
        nats://nats:6222
      ]
    }
```
We can then start NATS with `gnatsd -c /path/to/nats.conf` and be done with it. The only downside I can think of ATM is that this forces users to understand and deal with the NATS config syntax—but maybe that's not terrible? WDYT @pires?
